# nginx configuration — Mac 2 (10.7.3.73)
# Reverse proxy / load balancer / TLS termination

# Round-robin upstream — Backend A and Backend B
upstream backends {
    server 10.7.26.81:3001 max_fails=1 fail_timeout=10s;
    server 10.7.6.162:3002 max_fails=1 fail_timeout=10s;
}

# HTTP server — port 80
server {
    listen 80;
    server_name app.team1.test api.team1.test;

    location / {
        proxy_pass http://backends;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# HTTPS server — port 443
server {
    listen 443 ssl;
    server_name app.team1.test api.team1.test;

    ssl_certificate     /Users/utkarshjain/team1-tls/app.crt;
    ssl_certificate_key /Users/utkarshjain/team1-tls/app.key;

    location / {
        proxy_pass http://backends;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
